-- Server-side receipt OCR attempt limiter.
--
-- The Edge Function calls this only after it has authorized the booking guest
-- token (or an active dashboard user). An advisory transaction lock makes the
-- count-and-claim operation atomic, including for concurrent uploads. For a
-- grouped court booking, the function passes booking_group_ref so every row in
-- the group shares one quota.

create table if not exists public.receipt_verification_attempts (
  id bigint generated by default as identity primary key,
  booking_ref text not null,
  created_at timestamptz not null default now(),
  constraint receipt_verification_attempts_booking_ref_length
    check (length(booking_ref) between 1 and 160)
);

create index if not exists receipt_verification_attempts_booking_window_idx
  on public.receipt_verification_attempts (booking_ref, created_at desc);

alter table public.receipt_verification_attempts enable row level security;

-- This is anti-abuse and financial audit state. It is intentionally invisible
-- to browsers; the security-definer claim function is the only write path.
revoke all on table public.receipt_verification_attempts
  from public, anon, authenticated;
revoke all on sequence public.receipt_verification_attempts_id_seq
  from public, anon, authenticated;

create or replace function public.claim_receipt_verification_attempt(
  p_booking_ref text,
  p_max_attempts integer default 5,
  p_window_seconds integer default 600
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_booking_ref text := trim(coalesce(p_booking_ref, ''));
  v_now timestamptz := clock_timestamp();
  v_attempt_count integer := 0;
  v_first_attempt timestamptz;
  v_retry_after integer := 0;
begin
  if length(v_booking_ref) < 1 or length(v_booking_ref) > 160 then
    raise exception 'Invalid booking reference.' using errcode = '22000';
  end if;
  if p_max_attempts < 1 or p_max_attempts > 20 then
    raise exception 'Invalid receipt attempt limit.' using errcode = '22000';
  end if;
  if p_window_seconds < 60 or p_window_seconds > 3600 then
    raise exception 'Invalid receipt attempt window.' using errcode = '22000';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('receipt-verification|' || v_booking_ref, 0)
  );

  select count(*)::integer, min(created_at)
    into v_attempt_count, v_first_attempt
  from public.receipt_verification_attempts
  where booking_ref = v_booking_ref
    and created_at > v_now - make_interval(secs => p_window_seconds);

  if v_attempt_count >= p_max_attempts then
    v_retry_after := greatest(
      1,
      ceil(extract(epoch from (
        v_first_attempt + make_interval(secs => p_window_seconds) - v_now
      )))::integer
    );
    return jsonb_build_object(
      'allowed', false,
      'attemptsRemaining', 0,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  insert into public.receipt_verification_attempts (booking_ref, created_at)
  values (v_booking_ref, v_now);

  return jsonb_build_object(
    'allowed', true,
    'attemptsRemaining', p_max_attempts - v_attempt_count - 1,
    'retryAfterSeconds', 0
  );
end;
$$;

revoke all on function public.claim_receipt_verification_attempt(text, integer, integer)
  from public, anon, authenticated;
grant execute on function public.claim_receipt_verification_attempt(text, integer, integer)
  to service_role;
